version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.15.0
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn release
