version: 2
jobs:
  release:
    docker:
      - image: 'circleci/node8'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      # - run:
      #     name: release
      #     command: yarn release || true
